color: null
fieldLayouts:
  60ba6bc7-63f3-42a9-bbe4-9d8e772dd72e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-30T14:12:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6af7f648-fbf9-436b-849d-7428a8c61941
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-30T14:15:44+00:00'
            elementCondition: null
            fieldUid: ee23eee0-31b7-4cda-b63d-134aa4586e5d # Image Module
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecfdfdce-fb6a-49ea-a1d2-47cf6d677393
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-30T14:15:44+00:00'
            elementCondition: null
            fieldUid: 581f2422-3e50-4bed-bfac-2947bbfc9c66 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62a7cad8-2808-482b-91a2-7f63f048b333
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 873c4877-d9d7-4f64-886f-b7ddaa6d2141
        userCondition: null
handle: carouselSlide
hasTitleField: true
icon: null
name: 'Carousel Slide'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
