color: null
fieldLayouts:
  cfea3f32-00f4-4dde-9a4b-730dbddd48ff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T10:01:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 24218f54-6093-4e68-aa1b-d910acbab12a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T10:08:41+00:00'
            elementCondition: null
            fieldUid: 5f6b13a2-8f09-4cbf-a660-449cf3604a04 # Gallery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da1240e5-3a6d-4f6f-b32f-28fd0010b276
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3271ea8e-3469-4ef3-bb17-1b1a50a833e2
        userCondition: null
handle: gallerySection
hasTitleField: true
icon: null
name: 'Gallery Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
