color: null
fieldLayouts:
  e6076a7b-99f6-493b-91ab-711efee17898:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-16T15:59:47+00:00'
            elementCondition: null
            fieldUid: baf2428a-f9ee-4005-a0ea-a3574f7e6c1a # Panel Order
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2449bfd7-05d1-4594-90e1-4356818de0e6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-16T12:26:25+00:00'
            elementCondition: null
            fieldUid: ee23eee0-31b7-4cda-b63d-134aa4586e5d # Image Module
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fad07381-53dc-4327-9799-11574189c894
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-16T13:37:45+00:00'
            elementCondition: null
            fieldUid: cb07ea78-f11a-4d8f-9c74-c7b98efd05ab # Text Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e4a46c2-308b-4f44-80e3-acc72e30dc05
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-16T14:36:09+00:00'
            elementCondition: null
            fieldUid: 7909f48a-c93c-4744-b777-adfa4e087c46 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b437d2d-56b1-4de1-8f7e-8c7dde923d14
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 89cb46a1-c526-4bfe-8bce-ebeaf4fe6591
        userCondition: null
handle: imageTextPanel
hasTitleField: false
icon: null
name: 'Image / Text Panel'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
