color: null
fieldLayouts:
  e1a3640d-af8e-4e5d-bce1-f10652d9a92b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-16T11:42:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d9a6f6e7-5fd2-4e86-8b90-812942d1a601
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-16T11:44:23+00:00'
            elementCondition: null
            fieldUid: 8fd5d66a-69fe-418d-b9bc-957d2903d6bf # Page Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e56812a5-3454-4b8b-aa6a-ee872b6e7092
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 529f7e4a-df03-4081-8881-3f541fd12dc7
        userCondition: null
handle: pageTitles
hasTitleField: true
icon: null
name: 'Page Titles'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
