color: null
fieldLayouts:
  0f6f66aa-ce6d-4444-8151-f18b82572b97:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-23T01:12:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6b5ade1c-ec3f-4550-8bae-234a4ebecbff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-23T01:20:55+00:00'
            elementCondition: null
            fieldUid: e3b4d157-e782-41a9-9d54-503bf17adefb # Timeline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c429dcdb-acd0-4df1-a2f3-ad66f9a6a82b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a7b46326-f2c2-41f4-aa2e-c6aa89e7613e
        userCondition: null
handle: timelineSection
hasTitleField: true
icon: null
name: 'Timeline Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
