color: null
fieldLayouts:
  5baf8b23-d92b-43b0-9d47-02398230bd00:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-31T10:05:36+00:00'
            elementCondition: null
            fieldUid: cb07ea78-f11a-4d8f-9c74-c7b98efd05ab # Text Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c4ddb55-70c1-4b06-953c-a9de8acc6dfe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fdf1291f-c3e5-4a65-baba-1de6ed6146f4
        userCondition: null
handle: universeSection
hasTitleField: false
icon: null
name: 'Universe Section'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
