color: null
fieldLayouts:
  1bc5b4cc-130c-4e14-8ead-0d5396829d5e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-20T16:53:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cd193dd1-c6ff-4b69-a275-cd86410d05cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-20T16:55:23+00:00'
            elementCondition: null
            fieldUid: c4fdd5ce-34b0-424a-8625-0d1236549f54 # Senior Leadship
            handle: widerTeam
            includeInCards: false
            instructions: null
            label: 'Wider Team'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1071eb2-372b-41b1-96a7-2918e926360c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 434c78e1-8a6d-4d43-9a92-3801576e0b50
        userCondition: null
handle: widerTeamPanel
hasTitleField: true
icon: null
name: 'Wider Team Panel'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
