altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a8db73e9-e029-4452-b883-62999db5ee8b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-14T14:50:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 575e2a48-c461-4cc2-b9f6-1f72b8343fd2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c59b6845-a384-4ea3-ae87-11c8b5a3f31a
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
