columnSuffix: null
handle: contactLeftColumn
instructions: null
name: 'Left Column'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 8583166f-76ba-41de-957a-f28560286afe # Contact Details
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
