columnSuffix: null
handle: linkElement
instructions: null
name: Link
searchable: false
settings:
  advancedFields:
    - target
    - title
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - '1'
            -
              - allowAnchors
              - '1'
  types:
    - entry
    - url
    - email
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
