columnSuffix: null
handle: pageIntro
instructions: null
name: 'Page Intro'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 48af43a3-402f-405f-a299-1a77f1631683 # Restricted Editor
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
