columnSuffix: null
handle: peopleBio
instructions: null
name: Bio
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 8
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
