columnSuffix: null
handle: selectedDevelopments
instructions: null
name: 'Selected Developments'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add Development'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:70ac8027-90bd-41ac-9160-0d79d10f4f7d' # Portfolio
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
