columnSuffix: null
handle: textContent
instructions: null
name: 'Text Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: b0b3a5bb-2183-4595-b7d0-6fc449aeee81 # Custom Styles
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
