columnSuffix: null
handle: universeLink
instructions: null
name: Link
searchable: false
settings:
  advancedFields:
    - target
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - singles
                - 'section:70ac8027-90bd-41ac-9160-0d79d10f4f7d' # Portfolio
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
