defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 580e0a2c-57fa-4e95-99cc-4d72c7d6222c # Contact Page
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  966432a0-b4ee-458a-a839-f2381951a549: # Avdoo
    enabledByDefault: true
    hasUrls: true
    template: contact.twig
    uriFormat: contact
type: single
