defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0222f4cd-e7da-4074-b027-1614f16e783c # Expertise Page
handle: expertise
maxAuthors: 1
name: Expertise
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  966432a0-b4ee-458a-a839-f2381951a549: # Avdoo
    enabledByDefault: true
    hasUrls: true
    template: expertise.twig
    uriFormat: expertise
type: single
