defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 448beb76-19c7-4ae6-ba50-8adb90c37bda # Homepage
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  966432a0-b4ee-458a-a839-f2381951a549: # Avdoo
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
