defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1ef12edb-4c09-4a06-a619-93cb9ed0cf35 # People Page
handle: people
maxAuthors: 1
name: People
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  966432a0-b4ee-458a-a839-f2381951a549: # Avdoo
    enabledByDefault: true
    hasUrls: true
    template: people.twig
    uriFormat: people
type: single
