defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 36f20234-2575-4641-8a7a-1af6bb03cd51 # Press Index
handle: portfolioIndex
maxAuthors: 1
name: 'Portfolio Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  966432a0-b4ee-458a-a839-f2381951a549: # Avdoo
    enabledByDefault: true
    hasUrls: true
    template: portfolio/index.twig
    uriFormat: portfolio
type: single
