defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 301a5e76-f215-4679-82b9-f09ab63712a9 # Universe
handle: universe
maxAuthors: 1
name: Universe
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  966432a0-b4ee-458a-a839-f2381951a549: # Avdoo
    enabledByDefault: true
    hasUrls: true
    template: universe/_entry.twig
    uriFormat: 'universe/{slug}'
type: channel
