defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0ec22b56-7fd5-4a37-b84b-93affb9c5568 # Universe Index
handle: universeIndex
maxAuthors: 1
name: 'Universe Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  966432a0-b4ee-458a-a839-f2381951a549: # Avdoo
    enabledByDefault: true
    hasUrls: true
    template: universe/index.twig
    uriFormat: universe
type: single
